___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
# Plotly and Cufflinks

Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

## Installation

In order for this all to work, you'll need to install plotly and cufflinks to call plots directly off of a pandas dataframe. These libraries are not currently available through **conda** but are available through **pip**. Install the libraries at your command line/terminal using:

    pip install plotly
    pip install cufflinks

** NOTE: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

## Imports and Set-up

In [7]:
import pandas as pd
import numpy as np
%matplotlib inline

In [6]:
pip install cufflinks

Collecting cufflinks
  Downloading cufflinks-0.17.3.tar.gz (81 kB)
     ---------------------------------------- 81.7/81.7 kB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.9.2 in c:\users\chara\anaconda3\lib\site-packages (from cufflinks) (1.21.5)
Requirement already satisfied: pandas>=0.19.2 in c:\users\chara\anaconda3\lib\site-packages (from cufflinks) (1.4.4)
Requirement already satisfied: plotly>=4.1.1 in c:\users\chara\anaconda3\lib\site-packages (from cufflinks) (5.9.0)
Requirement already satisfied: six>=1.9.0 in c:\users\chara\anaconda3\lib\site-packages (from cufflinks) (1.16.0)
Collecting colorlover>=0.2.1
  Downloading colorlover-0.3.0-py3-none-any.whl (8.9 kB)
Requirement already satisfied: setuptools>=34.4.1 in c:\users\chara\anaconda3\lib\site-packages (from cufflinks) (63.4.1)
Requirement already satisfied: ipython>=5.3.0 in c:\users\chara\anaconda3\lib\site-packages (from cufflinks) (7.31.1)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\chara\anaconda3\lib\site-packages (from cufflinks) (7.6.5)
Requirement already satisfied: pygments in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (2.11.2)
Requirement already satisfied: backcall in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.0)
Requirement already satisfied: jedi>=0.16 in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.18.1)
Requirement already satisfied: colorama in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.5)
Requirement already satisfied: matplotlib-inline in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.1.6)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.20)
Requirement already satisfied: pickleshare in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.7.5)
Requirement already satisfied: decorator in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.1.1)
Requirement already satisfied: traitlets>=4.2 in c:\users\chara\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.1.1)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\chara\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.5.2)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\chara\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (6.15.2)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\chara\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (1.0.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\chara\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\chara\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (5.5.0)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\chara\anaconda3\lib\site-packages (from pandas>=0.19.2->cufflinks) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\chara\anaconda3\lib\site-packages (from pandas>=0.19.2->cufflinks) (2022.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\chara\anaconda3\lib\site-packages (from plotly>=4.1.1->cufflinks) (8.0.1)
Requirement already satisfied: debugpy>=1.0 in c:\users\chara\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (1.5.1)
Requirement already satisfied: tornado>=6.1 in c:\users\chara\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (6.1)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\chara\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (7.3.4)
Requirement already satisfied: psutil in c:\users\chara\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (5.9.0)
Requirement already satisfied: packaging in c:\users\chara\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (21.3)
Requirement already satisfied: nest-asyncio in c:\users\chara\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (1.5.5)
Requirement already satisfied: pyzmq>=17 in c:\users\chara\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (23.2.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\chara\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->cufflinks) (0.8.3)
Requirement already satisfied: fastjsonschema in c:\users\chara\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\chara\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (4.16.0)
Requirement already satisfied: jupyter_core in c:\users\chara\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (4.11.1)
Requirement already satisfied: wcwidth in c:\users\chara\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->cufflinks) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\users\chara\anaconda3\lib\site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (6.4.12)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\chara\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\chara\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (21.4.0)
Requirement already satisfied: entrypoints in c:\users\chara\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (0.4)
Requirement already satisfied: pywin32>=1.0 in c:\users\chara\anaconda3\lib\site-packages (from jupyter_core->nbformat>=4.2.0->ipywidgets>=7.0.0->cufflinks) (302)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\chara\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\chara\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.13.1)
Requirement already satisfied: prometheus-client in c:\users\chara\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.14.1)
Requirement already satisfied: jinja2 in c:\users\chara\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.11.3)
Requirement already satisfied: nbconvert>=5 in c:\users\chara\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (6.4.4)
Requirement already satisfied: argon2-cffi in c:\users\chara\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (21.3.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\chara\anaconda3\lib\site-packages (from packaging->ipykernel>=4.5.1->ipywidgets>=7.0.0->cufflinks) (3.0.9)
Requirement already satisfied: bleach in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (4.1.0)
Requirement already satisfied: testpath in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.6.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.5.0)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.8.4)
Requirement already satisfied: defusedxml in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.7.1)
Requirement already satisfied: beautifulsoup4 in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (4.11.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.5.13)
Requirement already satisfied: jupyterlab-pygments in c:\users\chara\anaconda3\lib\site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\chara\anaconda3\lib\site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.0.1)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\chara\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.0.2)
Requirement already satisfied: argon2-cffi-bindings in c:\users\chara\anaconda3\lib\site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (21.2.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\chara\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\chara\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.3.1)
Requirement already satisfied: webencodings in c:\users\chara\anaconda3\lib\site-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (0.5.1)
Requirement already satisfied: pycparser in c:\users\chara\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->cufflinks) (2.21)
Building wheels for collected packages: cufflinks
  Building wheel for cufflinks (setup.py): started
  Building wheel for cufflinks (setup.py): finished with status 'done'
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68718 sha256=6df6fd4dcc5ba689ffa8b47a186072ed02a4f173c1a90555fcf11755ac40bb99
  Stored in directory: c:\users\chara\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks
Installing collected packages: colorlover, cufflinks
Successfully installed colorlover-0.3.0 cufflinks-0.17.3
Note: you may need to restart the kernel to use updated packages.

In [8]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__) # requires version >= 1.9.0

5.9.0

In [9]:
import cufflinks as cf

In [10]:
# For Notebooks
init_notebook_mode(connected=True)

In [11]:
# For offline use
cf.go_offline()

### Fake Data

In [12]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [13]:
df.head()

          A         B         C         D
0 -0.658162  1.659472 -1.900050  1.729670
1 -0.441153 -0.586218 -1.415073  0.171240
2  1.000053  1.355351 -0.983692  0.424198
3 -0.560545 -0.408079 -0.503565  2.013454
4  0.474981  1.194538  0.580304  0.506025

In [14]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [15]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [16]:
df.iplot(kind='scatter',x='A',y='B',mode='markers',size=10)

## Bar Plots

In [17]:
df2.iplot(kind='bar',x='Category',y='Values')

In [18]:
df.count().iplot(kind='bar')

## Boxplots

In [19]:
df.iplot(kind='box')

## 3d Surface

In [20]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df3.iplot(kind='surface',colorscale='rdylbu')

## Spread

In [21]:
df[['A','B']].iplot(kind='spread')

C:\Users\chara\anaconda3\lib\site-packages\cufflinks\plotlytools.py:849: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.

C:\Users\chara\anaconda3\lib\site-packages\cufflinks\plotlytools.py:850: FutureWarning:

The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.

## histogram

In [22]:
df['A'].iplot(kind='hist',bins=25)

In [23]:
df.iplot(kind='bubble',x='A',y='B',size='C')

## scatter_matrix()

Similar to sns.pairplot()

In [24]:
df.scatter_matrix()

# Great Job!